export default {
  trailingComma: 'es5',
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  printWidth: 160,
  bracketSameLine: true,
  htmlWhitespaceSensitivity: 'ignore',
  bracketSpacing: true,
  arrowParens: 'always',
  importOrder: [
    '^@jest/(.*)$',
    '<BUILTIN_MODULES>',
    '^constructs$',
    '^aws-cdk-lib$',
    '^aws-cdk-lib/(.*)$',
    '^@ac-it-development/(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@@helpers/(.*)$',
    '^[./]',
    '<TS_TYPES>',
    '<THIRD_PARTY_TS_TYPES>',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
  importOrderCaseInsensitive: true,
  overrides: [
    {
      files: '*.yml',
      options: {
        useTabs: false,
        tabWidth: 4,
        singleQuote: false,
      },
    },
  ],
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};
